references/dm6.py, requirements.txt
For dm6, replaces the appending of "chr" with the chrom_convert script. Also moves the wrappers submodule branch to current master.
Re-ran reference.snakefile and everything builds cleanly.
=> Chrom convert

references/dm6.py
I had accidently removed the print $0 statment from awk. This adds it
back.
=> Adds print back to awk.

common.py, config.yml, postprocess/adapters.py, postprocess/dm6.py, postprocess/ercc.py, postprocess/erccFisher.py, postprocess/phix.py, references.snakefile, requirements.txt, rnaseq.snakefile, test_config.yaml, travis-setup.sh
I have changed a few things and have the tests working. Going to poke around and a little and see if there is anything else we want to add. I have been running everything locally, will generate references on biowulf too.
`protected` works, but only changes permissions for files, folders are still writable which could be problematic.
May want to add a rule that does:
* Takes all files
* Calls dirname
* runs chmod 555 on the folders
Or we could just make a rule that runs:
`find /data/LCDB/lcdb-references -type d -exec chmod 555 {} \;`
Then touch some done file.
=> Battle test

config.yml, envs/references_env.yml, requirements.txt
These are some config updates that add mouse references, plus some extra fixes to requirements to get everything to run correctly.
=> minor config updates

WRAPPER_SLURM, clusterconfig.yaml, config.yml, references.snakefile
First round of wrapper and config. Needs more testing!
=> Cluster stuff

WRAPPER_SLURM, clusterconfig.yaml, config.yml, downstream/rnaseq-requirements.txt, downstream/rnaseq.Rmd, postprocess/hg38.py, references.snakefile, requirements.txt, rnaseq.snakefile
This is a multipurpose PR with fixes and improvements made while analyzing a human rnaseq DE experiment:
- adds cluster infrastructure files from #15 (and so supercedes that PR). These are not fully tested yet, but there's not a good way to test them on travis so I figured I'd just include what I have so far.
- various updates to human references. These have been run on biowulf, so our references are up to date with these changes
- minor snakefile improvements
- added a new `downstream` directory. In that dir is a requirements file and an `rnaseq.Rmd` file. The Rmd is suitably generic such that if `sampletable.tsv` has a `group` column, you'll at least get diagnostic plots and DE results for the group contrast. This is intended to be [heavily!] edited for each particular experiment. But …
=> updates to rnaseq workflow

requirements.txt, wrappers/test/test_deeptools.py, wrappers/wrappers/deeptools/bamCoverage/README.md, wrappers/wrappers/deeptools/bamCoverage/environment.yaml, wrappers/wrappers/deeptools/bamCoverage/wrapper.py, wrappers/wrappers/multiqc/environment.yaml
Creates a basic wrapper for deeptools bamCoverage.
=> Deeptools bamCoverage

references.snakefile
could not figure out how to get things change with the other PR, so just made a new one.
=> adds chromsize sort with LC_COLLATE

config/envs/annotationdbi.yaml
We're in the process of fixing a ton of bioconductor and R packages in bioconda. In the meantime, to get tests to pass I'm playing around with channel priorities and may need to pin some versions.
=> channel priority

ci/get-data.py, config/envs/annotationdbi.yaml, config/test_config.yaml, wrappers/test/raw_data_fixtures.py, wrappers/test/test_deeptools.py, wrappers/test/test_featurecounts.py, wrappers/wrappers/picard/collectrnaseqmetrics/environment.yaml
refactor tests to use smaller data so that hopefully travis-ci runs faster
=> use smaller data files

config/config.yml, config/envs/R_rnaseq.yaml, requirements.txt
Realized that I needed to add the annotation hub, gene list, and gffutils specific config to the `config.yaml`.
=> Add annotation hub

config/config.yml, config/test_config.yaml, lib/postprocess/dm6.py
I wanted to download the precomputed file for mapping old FBgns and symbols to current
=> Downloads the precomputed FlyBase annotations that map symbol, fbgn, and old annotations.

config/config.yml, config/test_config.yaml, lib/postprocess/dm6.py
We may want to adjust this later, but this adds all of the gene symbol synonyms.
=> Adds gene symbol synonyms.

chipseq.snakefile
=> ensure unique output is bam

config/clusterconfig.yaml, config/config.yml, rnaseq.snakefile
=> minor fixes

include/WRAPPER_SLURM
=> set latency wait time in wrapper to 300

.circleci/config.yml, .circleci/setup.sh, Dockerfile, ci/get-data.py, lib/postprocess/phix.py, requirements.txt, workflows/chipseq/Snakefile, workflows/rnaseq/Snakefile, wrappers/wrappers/fastqc/environment.yaml, wrappers/wrappers/spp/wrapper.py
New version of deeptools (>3.0.1) has a different way of specifing args for normalization. This PR fixes the bamCoverage commands and pins the deeptools version in requirements to be at least this version. Disabled control bams for plotFingerprint, now using `--smartLabels`, and reduced the number of samples. The net effect is to reduce run time and complexity of the rule.
The deeptools arg change was one of the reasons for the tests failing in #83; since I'm making the fixes here needed for that PR, I'm incorporating #83 here (and closed that one).
Tests were then failing because #83 filters out multimapping reads for chipseq. Turns out in our test data, there are then no reads left in the bam files. I've updated and regenerated the example data; …
=> Deeptools fixes

lib/chipseq.py, lib/patterns_targets.py, lib/postprocess/dm6.py, workflows/chipseq/Snakefile, workflows/chipseq/config/chipseq_patterns.yaml, workflows/chipseq/config/config.yaml, workflows/references/config/config.yaml, wrappers/wrappers/macs2/callpeak/wrapper.py, wrappers/wrappers/sicer/README.md, wrappers/wrappers/sicer/environment.yaml, wrappers/wrappers/sicer/wrapper.py
Add debugged SICER support to chipseq workflow. Add mappable genome proportion handling to SICER and general workflow. Add MACS2 handling of mappable genome count.
=> Sicer update 1

workflows/chipseq/config/config.yaml, wrappers/wrappers/sicer/wrapper.py
also remove other peak callers from repeated tests.
=> use CONDA_PREFIX to find sicer

workflows/rnaseq/downstream/helpers.Rmd
=> workaround to use proxy for annotationhub

.circleci/config.yml, ci/build-docs.sh, docs/getting-started.rst, docs/guide.rst, docs/index.rst, docs/workflows.rst
After moving to circleci, I never ported over the docs building.
=> build docs on circleci

.gitignore, include/references_configs/Dictyostelium_discoideum.yaml, include/references_configs/Drosophila_melanogaster.yaml, include/references_configs/ERCC.yaml, include/references_configs/Escherichia_coli.yaml, include/references_configs/Homo_sapiens.yaml, include/references_configs/Mus_musculus.yaml, include/references_configs/PhiX.yaml, include/references_configs/README.rst, include/references_configs/Saccharomyces_cerevisiae.yaml, include/references_configs/Schizosaccharomyces_pombe.yaml, include/references_configs/Wolbachia_endosymbiont_of_Drosophila_melanogaster.yaml, include/references_configs/test.yaml
Addresses #122; further cleanup coming in a separate PR.
=> split out references

.circleci/config.yml, docs/changelog.rst, docs/config-yaml.rst, docs/developers.rst, docs/index.rst, include/reference_configs/test.yaml, lib/common.py, requirements.txt, workflows/chipseq/Snakefile, workflows/references/Snakefile, workflows/rnaseq/Snakefile, workflows/rnaseq/config/clusterconfig.yaml, workflows/rnaseq/config/config_star.yaml
Finally . . .
This was actually pretty straightforward to add a new aligner, even one that requires a paired GTF when building the index.
=> add support for STAR

include/reference_configs/Schizosaccharomyces_pombe.yaml
Another small url change, this time for pombe.
=> Updates pombe gff url.

include/reference_configs/Homo_sapiens.yaml
This updates the human urls for v25 and v19.
=> Updates human gencode_v25 and v19 to reflect url changes.

.circleci/config.yml, .circleci/setup.sh, deploy.py, docs/changelog.rst, docs/deploy.rst, docs/getting-started.rst, docs/index.rst, requirements.txt
=> Add deploy script

docs/changelog.rst, include/adapters.fa, include/reference_configs/Drosophila_melanogaster.yaml, workflows/chipseq/Snakefile, workflows/chipseq/config/chipseq_patterns.yaml, workflows/rnaseq/Snakefile, workflows/rnaseq/downstream/rnaseq.Rmd
- KEGG results in rnaseq.Rmd were not being correctly added to all.enrich
- better cutadapt args (rm adapters file; check for adapters in both ends)
- auto-detect featureCounts `-p`
=> bugfixes and updates (v1.4.1 RC)

requirements.txt, workflows/rnaseq/Snakefile, workflows/rnaseq/downstream/helpers.Rmd, workflows/rnaseq/downstream/rnaseq.Rmd
Adding support for labeled MA plot #183
=> Updates to rnaseq.rmd

include/reference_configs/Schizosaccharomyces_pombe.yaml
Fixes #197 and now is towards v1.5rc
=> Fixes typo in spombe tag name.

workflows/rnaseq/Snakefile, workflows/rnaseq/config/rnaseq_patterns.yaml, workflows/rnaseq/downstream/rnaseq.Rmd
=> run featurecounts in a single stranded mode

workflows/rnaseq/downstream/helpers.Rmd, workflows/rnaseq/downstream/rnaseq.Rmd
Pulls out alpha and lfc.thresh into a separate chunk for use elsewhere.
=> Minor (lfc.thresh arg)

workflows/rnaseq/downstream/helpers.Rmd
Selection of significantly changed genes should respect the log2foldchange threshold.
=> Fix changed genes

workflows/rnaseq/Snakefile, workflows/rnaseq/config/multiqc_config.yaml, workflows/rnaseq/config/rnaseq_patterns.yaml, wrappers/test/test_rseqc.py
=> rm rseqc bam_stat

README.md, workflows/rnaseq/config/multiqc_config.yaml, workflows/rnaseq/downstream/helpers.Rmd, workflows/rnaseq/downstream/rnaseq.Rmd
These commits:
1. fill in gene symbols with whatever ID is given if finding a SYMBOL is unsuccesful, rather than NA
2. remove status checks from the multiqc fastqc section
3. clarify order of input for contrasts
4. clarify lfcThreshold adjustment in other sections of the rnaseq
=> Lilly 2020 02 21

workflows/rnaseq/Snakefile
Previously confined to only a single thread
=> Add threads argument to featurecounts

workflows/rnaseq/downstream/helpers.Rmd, workflows/rnaseq/downstream/rnaseq.Rmd
Replaces top.plots with a function returning a dataframe that includes all metadata from colData(dds). Optionally takes a list of genes to consider.
Then plots the top genes with facet_wrap in ggplot.
=> Update top.plots function

env.yml, include/reference_configs/Danio_rerio.yaml, include/reference_configs/Dictyostelium_discoideum.yaml, include/reference_configs/Drosophila_melanogaster.yaml, include/reference_configs/Gallus_gallus.yaml, include/reference_configs/Homo_sapiens.yaml, include/reference_configs/Macaca_mulatta.yaml, include/reference_configs/Mus_musculus.yaml, include/reference_configs/Rattus_norvegicus.yaml, include/reference_configs/Saccharomyces_cerevisiae.yaml, include/reference_configs/Schizosaccharomyces_pombe.yaml, include/reference_configs/test.yaml, include/requirements.txt, lib/common.py, test/test_configs/test_rnaseq_config.yaml, workflows/references/Snakefile, workflows/rnaseq/Snakefile, workflows/rnaseq/config/config.yaml, workflows/rnaseq/config/rnaseq_patterns.yaml
Adds rules, patterns, and additions to infrastructure to support kallisto quantification.
=> Support kallisto

.circleci/config.yml, ci/test_harness.py, deploy.py, docs/changelog.rst, docs/config-yaml.rst, docs/developers.rst, include/WRAPPER_SLURM, lib/helpers.py, lib/patterns_targets.py, test/test_configs/complex-dataset-rnaseq-config.yaml, test/test_configs/test_file_uri.yaml, test/test_configs/test_rnaseq_config.yaml, test/test_configs/test_sra_config.yaml, workflows/rnaseq/Snakefile, workflows/rnaseq/config/clusterconfig.yaml, workflows/rnaseq/config/config.yaml, workflows/rnaseq/config/rnaseq_patterns.yaml, workflows/rnaseq/downstream/gene-patterns.Rmd, workflows/rnaseq/downstream/rnaseq.Rmd
This PR works out the details of how the stranded arg should be handled, checked, and used in rules. It also improves the way the `strand_check` rule is run.
=> Strand arg improvements

workflows/chipseq/config/multiqc_config.yaml, workflows/rnaseq/config/multiqc_config.yaml
This supercedes #374, to get tests to run (I believe tests don't run from a fork).
=> update multiqc configs

include/reference_configs/Plodia_interpunctella.yaml, lib/postprocess/utils.py
- add NCBI Plodia references
- new `lib.postprocess.utils.extract_from_zip` function for working with this and other references coming from inside a zip file
=> add Plodia interpunctella reference config

workflows/rnaseq/Snakefile
Have STAR use disk memory for its temporary files.
=> Use tempdir, if configured, for STAR

lib/helpers.smk, workflows/variant-calling/Snakefile
add function in helpers to create dictionary of input files for snpeff and snpeff_cancer rules
make line formatting fixes
=> add function creating required dictionary of input files for snpeff rules
