lcdb/lcdb-wf

- .travis.yml
- common.py
- get-data.py
- requirements.txt
- test_config.yaml
- travis-setup.sh
Now that we have a decent framework for the wrapper tests, it was straightforward to add the tests here.
There's a `test_config.yaml` that gets the small fastqs, fasta, and gtf from lcdb test data.
This is currently failing because of HTTP 500 errors from the anaconda servers (which seems to happen periodically). The solution is to keep restarting the build.
> Travis tests

- bootstrap.py
- manifest.txt
This provides a way of cloning the repo into a new analysis directory.
The idea is that there's a whitelist (`manifest.txt`) of files in the repo that should be copied, anything not on the list is skipped.
```bash
git clone . tmpdir
cd tmpdir
git remote add upstream git@github.com:lcdb/lcdb-wf.git
git checkout -b newbranch
git rm $files-to-remove  # see below
git commit -m 'deleted stuff'
rsync tmpdir/ destdir/
```
Which files to delete from the temporary cloned repo: anything NOT matched by globs in `manifest.txt`, and  anything  that already exists in the destination dir.
> bootstrap script

- .buildkite/pipeline.yml
- .travis.yml
- ci/travis-setup.sh
- references.snakefile
- requirements.txt
- rnaseq.snakefile
- wrappers/README.md
- wrappers/test/conftest.py
- wrappers/test/raw_data_fixtures.py
- wrappers/test/test_atropos.py
- wrappers/test/test_bowtie2.py
- wrappers/test/test_cutadapt.py
- wrappers/test/test_demo.py
- wrappers/test/test_fastq_screen.py
- wrappers/test/test_fastqc.py
- wrappers/test/test_featurecounts.py
- wrappers/test/test_hisat2.py
- wrappers/test/test_kallisto.py
- wrappers/test/test_multiqc.py
- wrappers/test/test_picard.py
- wrappers/test/test_rseqc.py
- wrappers/test/test_samtools.py
- wrappers/test/utils.py
WIP . . . I'll update this when things stabilize.
**Update:**
This is an omnibus PR with substantial changes to the test framework. It includes the following changes:
- adds parallel testing support via `pytest-xdist`. Run pytest with `-n 6` to run in parallel with 6 cores.
- uses new data from `lcdb-test-data`'s `add-chipseq` branch for all wrapper tests
- pytest fixture reorganization. See `wrappers/README.md` for details. Basically fixtures are pulled out of `conftest.py` and put in the respective `test_<wrapper name>.py` file.
- most wrapper tests now use the "tiny" fastq and bam files for faster testing, relying on the full rnaseq.snakefile run as an integration test
- uses buildkite for testing in parallel on local infrastructure. This is currently in a 14-day trial period, so we …
> reorganization of tests

- ci/get-data.py
- config/envs/R_rnaseq.yaml
- config/sampletable.tsv
- downstream/rnaseq.Rmd
- rnaseq.snakefile
This adds a rule and necessary infrastructure for rendering a default rnaseq DE analysis based on the sampletable. Doing so required adding the other two samples from the example data.
I'd like to eventually add config options to the Rmd to choose the correct annotation db; currently you have to switch to e.g., `org.Hs.eg.db` manually. The `rnaseq.Rmd` is intended to be heavily edited anyway based on the particular experiment, so I'm not to worried about that.
> render rnaseq report

- .buildkite/pipeline.yml
- .gitignore
- .travis.yml
- ci/travis-setup.sh
- config/envs/R_rnaseq.yaml
- downstream/rnaseq.Rmd
This PR adds further improvements to rnaseq.Rmd.
- adds the import of salmon transcript-level counts into a DESeq object using the tximport package
- adds an example of using SVA and how to plot it vs other metadata to help with interpretation
- makes some fixes to the testing setup (use a shorter path to avoid conda complaining about 80-char limits; was hitting this for some R packages)
> tximport, salmon, sva

- .buildkite/pipeline.yml
- .gitignore
- .travis.yml
- ci/travis-run.sh
- ci/travis-setup.sh
- config/config.yml
- config/envs/R_rnaseq.yaml
- config/envs/annotationdbi.yaml
- config/test_config.yaml
- downstream/rnaseq.Rmd
- lib/common.py
- references.snakefile
- rnaseq.snakefile
This PR provides a general mechanism for getting CSVs of `gene_id` to any number of other accessions or metadata. 
This required some other changes, which I'm rolling into one big PR again. Specifically:
- we now get annotation lookup tables in the references dir (see below)
- arbitrary kwargs can now be supplied in the config YAML and are passed to conversion functions. The gffutils rule, genelist rule, and annotations rule now use this mechanism. See the updated config.yaml below for what it looks like.
- added ability to import salmon transcript-level counts into DESeq2
- the RMarkdown is now rendered; this needed some tweaking to the device in order for the tests to run headless
- lots of playing around with buildkite. After much deliberation I've decided it's not worth the additional …
> R annotation stuff

- references.snakefile
Found that chromsizes was not playing well with pybedtools because it was not sorted correctly. Just added as simple `sort -k1,1` to the command.
> adds a sort when creating chromsizes

- .travis.yml
- 4c.snakefile
- ci/travis-run.sh
- ci/travis-setup.sh
- config/envs/R_rnaseq.yaml
- lib/common.py
- references.snakefile
- requirements.txt
- rnaseq.snakefile
- wrappers/test/test_dupradar.py
- wrappers/test/test_picard.py
- wrappers/wrappers/atropos/environment.yaml
- wrappers/wrappers/bowtie2/align/environment.yaml
- wrappers/wrappers/bowtie2/build/environment.yaml
- wrappers/wrappers/demo/environment.yaml
- wrappers/wrappers/dupradar/environment.yaml
- wrappers/wrappers/fastq_screen/environment.yaml
- wrappers/wrappers/hisat2/align/environment.yaml
- wrappers/wrappers/hisat2/build/environment.yaml
- wrappers/wrappers/multiqc/environment.yaml
- wrappers/wrappers/picard/collectrnaseqmetrics/environment.yaml
- wrappers/wrappers/picard/markduplicates/environment.yaml
- wrappers/wrappers/rseqc/bam_stat/environment.yaml
- wrappers/wrappers/rseqc/geneBody_coverage/environment.yaml
- wrappers/wrappers/rseqc/infer_experiment/environment.yaml
- wrappers/wrappers/rseqc/tin/environment.yaml
An attempt to clean up individual snakefiles' boilerplate by having them import stuff from `lib.common` for setting up the shell, getting sampletables, and reference dirs.
Also improves docstrings.
**edit Jun 21 2017:** turns out bumping version was a huge pain. See https://github.com/lcdb/lcdblib/pull/41 for some details. I also figured out here that we need to pin R in order to avoid a readline error, and that the dupRadar package doesn't specify that it requires KernSmooth which used to be a built-in package but is no longer in the most recent R.
> refactor into common.py

- config/config.yml
This PR increments to the latest FlyBase version (r6.16). It also modifies method names for the post-processing steps that appear to have changed.
> Increment FlyBase to r6.16

- references.snakefile
Addresses #53 by letting AnnotationHub use tmpdir when downloading its databases.
> annotation hub uses tmpdir

- rnaseq.snakefile
- wrappers/wrappers/bowtie2/align/environment.yaml
- wrappers/wrappers/bowtie2/build/environment.yaml
- wrappers/wrappers/deeptools/plotFingerprint/environment.yaml
- wrappers/wrappers/demo/environment.yaml
- wrappers/wrappers/dupradar/environment.yaml
- wrappers/wrappers/fastq_screen/environment.yaml
- wrappers/wrappers/hisat2/align/environment.yaml
- wrappers/wrappers/hisat2/build/environment.yaml
- wrappers/wrappers/multiqc/environment.yaml
- wrappers/wrappers/multiqc/wrapper.py
- wrappers/wrappers/samtools/merge/environment.yaml
This PR affects environments, fixing the following issues:
1. if the conda installation is python2 (e.g., Miniconda2), then wrapper generation tries to use py27 even in cases where we have lcdblib (which is py3 only). So in those environment.yaml files, I've pinned `python =3`.
2. multiqc depends on spectra which depends on colormath which depends on networkx. The new version of networkx broke colormath, which in turn breaks multiqc. The fix is to pin networkx <2 in the multiqc environment
3. multiqc uses click, which very pointedly does not play nice with python3 (http://click.pocoo.org/5/python3/). We have been having problems getting it working in bioconda, so the latest multiqc versions are only available for py27. This was a problem as the wrapper also depended on the py3-only …
> Dependency updates

- config/envs/R_rnaseq.yaml
- config/test_config.yaml
- config/test_hub-config.yaml
- docs/getting-started.rst
- downstream/rnaseq.Rmd
- lib/common.py
- lib/rnaseq_trackhub.py
- requirements.txt
- rnaseq.snakefile
This PR dramatically improves the usability and functionality of the rnaseq.Rmd file, simplifying it while at the same time making it more general.
- Improved comments and detailed function help (using roxygen syntax)
- Anything that might need to be changed is marked with `# Assumption:`
- OrgDb is now specified as a string and libraries are loaded accordingly
- Placeholder link to UCSC track hub with placeholder params for session, location, and hub to load
- Dot plots of normalized gene counts now have nicer titles (with symbol & alias by default)
- There is now a `res.list`, which holds results of various experiments and/or different contrasts for the same experiment. This is iterated over, generating RMarkdown headers, summary tables, normalized count dot plots, MA-plots, and pval …
> RNA-seq Rmd overhaul

- config/envs/R_rnaseq.yaml
- config/test_config.yaml
- config/test_hub-config.yaml
- docs/getting-started.rst
- downstream/rnaseq.Rmd
- lib/common.py
- lib/rnaseq_trackhub.py
- requirements.txt
- rnaseq.snakefile
This brings the track hub creation up to use the new trackhub features (staging, single rsync call, simplified filenames, py3 support).
Replaces #50, and also adds the ability to include custom "supplemental" files in the hub (see at the end of `config/test_hub_config.yaml`).
Edit: additional tweaks were needed to get tests to pass like a new annotationhub accession for fly and some changes to the R_rnaseq envrionment.
> Trackhub fixes

- config/config.yml
- references.snakefile
sqlite3 is really slow on biowulf's shared filesystem; this ensures that if there's lscratch provided the gffutils db will be created there and then moved over.
Also adds human GENCODE v25 gfftutils db, which took about 40 mins to create from a 2.5M line GTF using the settings updated here.
> improve gffutils db creation

- chipseq.snakefile
- ci/get-data.py
- config/chipseq-sampletable.tsv
- config/sampletable.tsv
- rnaseq.snakefile
It's currently undocumented (unless you read the snakefiles) that you can provide an `orig_filename` column to the sampletables and have them automatically symlinked over to sample directories. Super useful for mapping annoying core filenames over to something more meaningful. This PR modifies the example data download to use a different directory structure, and uses the `orig_filename` column in the sampletables to map the files in the new structure over to where they're expected. That way 1) the functionality is more discoverable and 2) it's actually tested now.
> add orig_filename to sampletables

- .travis.yml
- ci/travis-run.sh
- requirements.txt
- workflows/external/Snakefile
Downloads and fixes a couple of modENCODE data files, as an example of downloading and fixing (and lifting over) external data.
> add example external workflow

- .gitignore
- .travis.yml
- ci/travis-run.sh
- workflows/chipseq/config/clusterconfig.yaml
- workflows/colocalization/Snakefile
- workflows/colocalization/config/config.yaml
- workflows/colocalization/scripts/colocalization_heatmap.py
- workflows/external/Snakefile
This PR adds a colocalization workflow, which runs IntervalStats, jaccard, fisher, and GAT on a bunch of bed files and then plots heatmaps of pairwise colocalization. While I've had this workflow kicking around for a while, it was never integrated well into any chipseq workflows and always required hand-editing the config file.
Now, using the updated system of subworkflows and separate patterns/targets files, it's possible to configure a new chipseq run in `workflows/chipseq/config/config.yaml` . . . and then with _no other changes_, run the colocalization workflow and it will run the peak-calling for the new run in the chipseq workflow, then run all the newly necessary pairwise comparisons, and finally propagate all the way out to a new row and column in the colocalization heatmaps.
It's …
> Colocalization workflow

- workflows/chipseq/config/multiqc_config.yaml
- workflows/rnaseq/config/multiqc_config.yaml
- Fixes pulling in fastq_screen and picard/RNASeqMetrics multiqc.
- Starts to try to address the same issue with picard/markdups, but it still is not working.
For markdups I have tried adding:
- `fn: `
- `contents: `
- `contents_re:`
But none of these are working.
> Add multiqc patterns

- workflows/chipseq/Snakefile
- workflows/chipseq/config/clusterconfig.yaml
- updates `TEST SETTINGS` comments to use 24g rather than 32g to avoid allocating more RAM than is available (despite requesting that much from the cluster...)
- fixes the macs2 cluster config
- adds `fingerprint` and `merge_techreps` to clusterconfig
> Minor chipseq updates

- requirements.txt
- workflows/chipseq/Snakefile
- workflows/chipseq/config/multiqc_config.yaml
- workflows/rnaseq/Snakefile
- workflows/rnaseq/config/multiqc_config.yaml
This PR overhauls the MultiQC config for both RNA-seq and ChIP-seq:
- general stats table is now much less confusing, as rows for different stages (raw, cutadapt, bam) are effectively merged into columns
- running fastqc module separate times (raw, trimmed, aligned) gives different sections and also gives the corresponding columns in the general stats table
- ordering of modules reflects the workflow
- general stats columns are organized so that the different stages of fastqc can be directly compared to each other
- better column names and better ordering for the libsizes table
- plotFingergprint logs will now make it into the multiqc report
> Multiqc tweaking

- workflows/colocalization/scripts/colocalization_heatmap.py
- workflows/figures/Snakefile
- workflows/figures/packager.sh
- workflows/figures/scripts/peak_count.py
- workflows/figures/scripts/peaks_at_promoters.py
- workflows/figures/style.css
- workflows/figures/updates.rst
This PR updates the `figures` workflow to reflect what I've been using for a couple of projects now.
The docstring at the top of the Snakefile has some details, but briefly:
- Each script in `scripts/scriptname.py` is expected to create, at a minimum, `figures/scriptname/README.txt` in ReST format. The script can create anything else it needs to, but I generally only track the README as an output in the Snakefile. The README is typically written only at the very end of the script so that everything else in it successfully completes.
- Each script has its own rule in the figures Snakefile; that's where input deps are configured
- The final outputs from rnaseq and chipseq workflows are symlinked over to the figures dir (including their respective multiqc.html files) so that there's a single …
> Figures workflow overhaul

- include/WRAPPER_SLURM
- include/bigBroadPeak.as
- include/bigNarrowPeak.as
- lib/chipseq.py
- requirements.txt
- workflows/chipseq/Snakefile
- workflows/chipseq/chipseq_trackhub.py
- workflows/chipseq/config/clusterconfig.yaml
- workflows/chipseq/config/config.yaml
- workflows/chipseq/config/hub_config.yaml
We finally have a trackhub with peaks for chipseq . . .
The `bed_to_bigbed` rule detects the format of the output bed files and uses the corresponding autoSql file, which can be found in `include/`. Currently supports narrowPeak from `macs2` and `spp`, and broadPeak from `macs2 --broad`.
The track hub codes figures out which subgroups to add to each bigBed track. For easy cases where a single IP BAM is provided to the peak-calling run, we can just grab the corresponding row in the sampletable, and use the values of the columns for that row as the subgroups. For cases where there are multiple IPs provided, the solution is to only provide the subgroup if there is only a single unique value for a column across all of the IPs provided. Otherwise the subgroup's value is set to `"NA"`.
I think …
> Chipseq additions

- .circleci/config.yml
- workflows/chipseq/chipseq_trackhub.py
- workflows/chipseq/config/config.yaml
- workflows/rnaseq/Snakefile
- workflows/rnaseq/config/config.yaml
- workflows/rnaseq/config/hub_config.yaml
- workflows/rnaseq/config/rnaseq_patterns.yaml
- workflows/rnaseq/rnaseq_trackhub.py
If using a TruSeq kit (where pos strand corresponds to antisense transcription), you had to either muck around in `rnaseq_trackhub.py` to get things configured correctly (possibly messing up the track labels), or change the params for deepTools bamCoverage to filter out a different strand.
To make this less annoying, there are now *pos* and *neg* bigWigs as well as *sense* and *antisense* symlinks.
We're now operating under the following assumptions:
- deepTools **always** generates bigWigs with "pos" in the extension for reads mapping to the positive strand of the reference and bigWigs with "neg" in the extension for reads mapping to the negative strand of the reference. *This is independent of sense or antisense transcription*.
- `rnaseq_trackhub` **only** pays attention to *sense* and …
> Trackhubs and stranded bigwigs

- workflows/rnaseq/Snakefile
In some cases we were running into problems where the symlink generation was getting confused about filenames. I haven't been able to reliably reproduce it, but I think this should address the issue and is an improvement anyway.
Instead of running once per fastq, the symlinking rule runs just once and does all the symlinks in one shot. Without wildcards in the input/output, we should avoid any confusion.
> bundle symlinks so the rule only runs once

- workflows/chipseq/Snakefile
- workflows/chipseq/config/chipseq_patterns.yaml
This PR uses deepTools' `multiBigwigSummary` and `plotCorrelation` on the generated bigWigs to get a clustered heatmap of chipseq samples.
In addition to a PNG heatmap (currently configured as `{agg_dir}/deeptools/correlation_heatmap.png`), there's also a TSV correlation matrix (`{agg_dir}/deeptools/plotcorrelation.tab`). The idea is that this TSV can be easily incorporated into whatever ChIP-seq report we end up creating.
> add clustered heatmaps for chipseq

- workflows/chipseq/Snakefile
- workflows/rnaseq/Snakefile
If a sampletable has the column "Run" (case-sensitive) and at least one item in it starts with "SRR", then assume that column refers to SRA runs, and download the data directly from SRA, gzip it, and put it into the sample dirs.
This means you can download a table from the SRA Run Selector, add your own first column that the workflow will use to create sample directories, and use the sampletable for downstream RNA-seq DE with no further changes.
This also opens up the possibility of supplying example config files + sample tables that are also tested on biowulf to generate example outputs to demonstrate output.
Note that this functionality is NOT yet tested on CircleCI. Not quite sure how to do that yet. Maybe have a separate task in the CircleCI workflow that only does `snakemake -U …
> add support for downloading directly from SRA

- .circleci/config.yml
- ci/preprocessor.py
- workflows/chipseq/Snakefile
- workflows/rnaseq/Snakefile
There are cases where, due to our minimal test data and/or test hardware, we need to use particular settings to make the tests work on CircleCI. For example, Java args for MarkDuplicates can't use 32G of allocated memory on CircleCI.
Previously, these restrictions were written right into the code, and it was up to the user to edit them upon using the workflows for actual work. That was not only inconvenient, but could also introduce errors (for example, by forgetting to uncomment the CPM normalization when making RNA-seq bigWigs).
Now, we run the new `ci/preprocessor.py` on the Snakefiles before testing them. The doctests from that script are run immediately before using it on the Snakefiles to minimize errors in the preprocessing.
See the docstring for `ci/preprocessor.py` for details, …
> preprocess files before testing

- workflows/rnaseq/Snakefile
Current default Xmx arguments to picard collectrnaseqmetrics and markduplicates lack leading dash.
> Xmx leading dash in default picard arguments

- workflows/rnaseq/Snakefile
This is a weird one. I tried actually setting the picard java VM ram to 32g and repeatedly got segfaults, which remained if I increased ram, messed with the clusterconfig ram setting, made there be bigger separation between VM memory and node ram, etc.
What ended up working was _reducing_ the VM ram, based on looking at prior RNAseq snakefiles that had worked ok. I guess this is just some issue with incorrect handling of large memory allocations? Whatever it is, it definitely fixes the issue for me. That being said, I would certainly not object to waiting until this is replicated.
> picard java VM memory reduction

- wrappers/wrappers/dupradar/wrapper.py
In the rnaseq workflow, dupradar calls Rsubread/featurecounts, which emits a temporary file in the directory from which the pipeline is run. It's around 500M in my current pipeline, and I don't think it's introducing race conditions or anything but it's impolite and asymptotically problematic.
This proposed fix modifies the dupradar wrapper to: create a temporary directory via python tempfile, pass the directory to dupradar and Rsubread via the hidden "tmpDir" argument, and then clean up the temporary directory when the R run completes.
Note that this fixes the only temporary file I've noticed the dupradar wrapper emitting, but I suppose it's possible there are others that I'm missing that this doesn't fix, as it only passes tmpDir to one internal call to Rsubread.
> dupradar: point embedded featurecounts to tmp

- workflows/rnaseq/downstream/rnaseq.Rmd
Hopefully it works EVEN BETTER this time.
So the current example in workflows/rnaseq/downstream/rnaseq.Rmd of using lfcThreshold=2 is actually secretly not doing anything different than the example without lfcThreshold specified. This is because lfcShrink ignores results-style arguments other than (exactly one of) coef or contrast. In order to get lfcShrink to work with nonstandard results calls, one must first call results with no shrinkage and the custom analysis request, and then call lfcShrink providing both the dds object and the results table from the separate results call.
And in the process of testing the first fix, several downstream things broke when my test dataset contained no actual DE genes when lfcThreshold=2. This is in upset plot handling and DEGreport patterning after …
> Custom results call using lfcShrink

- lib/chipseq.py
- lib/patterns_targets.py
- lib/postprocess/dm6.py
- workflows/chipseq/Snakefile
- workflows/chipseq/config/chipseq_patterns.yaml
- workflows/chipseq/config/config.yaml
- workflows/references/config/config.yaml
- wrappers/wrappers/macs2/callpeak/wrapper.py
- wrappers/wrappers/sicer/README.md
- wrappers/wrappers/sicer/environment.yaml
- wrappers/wrappers/sicer/wrapper.py
Adds SICER support to ChIP-seq workflow. Uses new bioconda recipe.
Adds mappable genome fraction support to SICER, by specifying various genome sizes in config and then injecting that information into the run block.
Adds mappable genome count support to MACS2, using similar methods as with SICER.
> SICER integration in ChIP-seq. Mappable genome handling in ChIP-seq.

- lib/postprocess/dm6.py
- workflows/chipseq/config/config.yaml
- workflows/references/config/config.yaml
- wrappers/wrappers/sicer/README.md
- wrappers/wrappers/sicer/wrapper.py
First attempt at addressing comments raised by Ryan Dale. Handles reference data processing much more cleanly. Adapted several SICER wrapper modifications for legibility. Modified shell cd to tmpdir and call to protect against one possible runtime error.
> Cleaner FlyBase chr processing; attempt at fixing SICER ci failure

- .circleci/config.yml
- lib/chipseq.py
- lib/patterns_targets.py
- lib/postprocess/dm6.py
- workflows/chipseq/Snakefile
- workflows/chipseq/config/chipseq_patterns.yaml
- workflows/chipseq/config/config.yaml
- workflows/references/config/config.yaml
- wrappers/wrappers/macs2/callpeak/wrapper.py
- wrappers/wrappers/sicer/README.md
- wrappers/wrappers/sicer/environment.yaml
- wrappers/wrappers/sicer/wrapper.py
Candidate code for SICER integration into ChIP-seq pipeline. Features:
-SICER runs now supported in ChIP-seq using similar method as with MACS2 and spp. 
-mappable genome proportion or count is now available to peak callers in each run block by injection from the config file.
-SICER and macs2 wrappers both intercept user-specified or genome-default mappable genome information and specify it to the program call.
> SICER integration and mappable genome handling

- ci/get-data.py
- workflows/chipseq/config/config.yaml
- workflows/references/config/config.yaml
- workflows/rnaseq/config/config.yaml
- workflows/rnaseq/downstream/rnaseq.Rmd
All recent versions of rnaseq.Rmd with count reporting are wrong if the DESeq2 results tables are not already sorted by ascii sort on gene ID. This should patch the issue by forcing sorting to be synchronized.
> Fix sorting error when adding count data to output

- docs/references-config.rst
- docs/tests.rst
- include/reference_configs/test.yaml
- lib/common.py
- workflows/references/Snakefile
Some minor fixes to the recently merged "simplify-patterns" branch. Clarifications in docs, use new mappings in test config, and be less noisy about warnings.
> Simplify patterns fixes

- requirements.txt
- workflows/chipseq/config/multiqc_config.yaml
- workflows/rnaseq/config/multiqc_config.yaml
Removed some config items that are no longer needed; they otherwise cause multiqc v1.6 to hang.
> update multiqc configs to work with v1.6

- docs/cluster.rst
- docs/references-config.rst
- docs/workflows.rst
- lib/cluster_specific.py
- lib/common.py
- workflows/chipseq/Snakefile
- workflows/colocalization/Snakefile
- workflows/external/Snakefile
- workflows/figures/Snakefile
- workflows/references/Snakefile
- workflows/rnaseq/Snakefile
This PR pulls out the "tempdir_for_biowulf" function from `lib/common.py` and puts it in a new `lib/cluster_specific.py`. That way there is a single place to put cluster-specific details.
I updated the docs to reflect this, and to point out what needs to change to make things work on a different cluster.
> Cluster-specific details

- test/test_configs/test_sra_sampletable.tsv
- workflows/references/Snakefile
- workflows/references/config/clusterconfig.yaml
- workflows/rnaseq/Snakefile
- test single-end and paired-end SRA downloads in the same sampletable
- be smarter about PE/SE detection from sampletable in fastq_dump rule
- fix typo in fastq_dump PE download
- move references workflow's chromsizes rule away from a localrule, since human and mouse needed a lot of RAM (@esnaultc this merges the `function_changes` branch)
> various cleanups

- .circleci/config.yml
- .circleci/setup.sh
- include/WRAPPER_SLURM
- requirements.txt
- workflows/chipseq/Snakefile
- workflows/rnaseq/Snakefile
This took soooo much more work than it should have (had to throw out most of #146 after spending a ton of time on it).
1. Wrappers are now only used for cases where we actually need the independent environment (e.g., where py2 is required). The remainder are used as scripts rather than wrappers. This allows them to use the main environment, and cuts down a lot on env creation at run time.
2. There was a big mess with fastqc's java VM complaining about fonts, which actually didn't stop the workflow but instead just hung. Now fastqc is using the global env which seems to have solved it. I believe this was related to an interaction between the conda channels we were using and the conda channels indicated in the environment.yaml. Specifically, we weren't pulling the right openjdk from …
> Fix issue 145 (redo)

- test/test_configs/override.yaml
- test/test_configs/star_override.yaml
- workflows/rnaseq/Snakefile
- workflows/rnaseq/config/config.yaml
- workflows/rnaseq/config/rnaseq_patterns.yaml
- workflows/rnaseq/rnaseq_trackhub.py
This pull request removes the bigwig symlinking step from the workflow. This is in response to our discussion about #179 , during which we decided to scrap the symlinking and make a sort of checkpoint qc step that confirms the strandedness (among other things) before creation of the bigwigs.  The following files were modified:
- 'workflows/rnaseq/Snakefile' (removed the rule 'symlink_bigwigs')
- 'workflows/rnaseq/config/rnaseq_patterns' (removed the 'sense' and 'antisense' entries from the 'bigwig' section
-'workflows/rnaseq/config/config.yaml'  (replaced 'sense' and 'antisense' with 'pos' and 'neg' in the 'merged_bigwigs' section
> removed bigwig symlinking

- .gitignore
- docs/references-config.rst
- include/reference_configs/test.yaml
- lib/common.py
- requirements.txt
- workflows/references/Snakefile
- workflows/rnaseq/Snakefile
- workflows/rnaseq/config/rnaseq_patterns.yaml
This PR adds support for RSeQC's [infer_experiment.py](http://rseqc.sourceforge.net/#infer-experiment-py) as a replacement for the featurecounts' s0, s1, s2 runs.
MultiQC picks up the infer_experiment output and puts it into a nice plot making it very easy to identify sense/antisense libraries. By the way, the existing `utils.flatten(c.targets['rseqc'])` already in the inputs of the multiqc rule doesn't need to be changes, as the new pattern/target is part of that section of the patterns yaml.
infer_experiment needed a bed12 file, so there's a new rule and a new conversion in the references workflow -- along with associated documentation.
There were some additional R packages that seemed to be missing when I was running locally so I added them, too.
> rseqc infer_experiment

- .circleci/config.yml
Fixes #182. The issue was that the ssh key needs to be added *right* before the final push step. This also uses a newly-configured read/write key.
> fix docs building

- .circleci/config.yml
- lib/helpers.py
- lib/patterns_targets.py
- test/test_configs/test_pe_sampletable.tsv
- test/test_configs/test_sra_sampletable.tsv
- test/test_configs/two_samples.tsv
- workflows/rnaseq/Snakefile
- workflows/rnaseq/config/sampletable.tsv
Addresses #175 by removing support for experiments where some samples are SE and some samples are PE.
As described in #175, supporting such mixed layouts was over-complicating the code with marginal benefit.
This PR:
- adds a `is_paired` attribute to SeqConfig objects (plus requisite infrastructure to do so)
- updates RNA-seq snakefile to pay attention to the new attribute, while simplifying other code
- raises ValueError and prints the sample names that are inconsistent (chooses to report SE or PE consistencies based on which is smaller to avoid spamming stdout with many samples)
- reenables the SRA test
- adds a separate PE test (and corresponding sampletable)
- RNA-seq tests will only run if the dry-run test works, which should hopefully short-circuit spurious tests on circle-ci.
> Require all SE or all PE

- .circleci/config.yml
- deploy.py
Previously, if a user ran the tests and then deployed right from that directory, some of the test output would be inadvertently copied over. This PR improves the deployment script to only ever pay attention to files under version control.
The tests have also been reconfigured so that they first use the deployment script and then run the tests over in the deployed directory. This test more closely matches real-world usage and ensures that everything is properly deployed.
It also adds an optional argument to build the conda env in the destination.
> tests use results from deploy script

- .circleci/config.yml
This PR takes advantage of the CircleCI feature to [upload artifacts](https://circleci.com/docs/2.0/artifacts/) that can be downloaded from the respective test's artifacts tab.
Currently:
- chipseq test uploads `multiqc.html`
- rnaseq test uploads 
- a zip of the entire `downstream` directory
- the rendered `rnaseq.html`
- `multiqc.html`
- report-env job uploads the `env.yaml` of the successfully-created environment (and the `env-r.yaml` of the successfully-created R environment).
It may be possible to build the docs such that they pull the latest artifacts, so that the various reports in their most recent state are hosted directly in the docs as examples.
> try uploading artifact

- .circleci/config.yml
- workflows/rnaseq/Snakefile
It's always been annoying to me to run most of the way through the workflow only to realize that the strandedness of the library was not what I originally thought. This PR adds a rule that you can run at the beginning of a project (immediately after setting up the sampletable and config). The rule does not enter the DAG; you need to explicitly ask for it from the command line.
Run it like this:
```bash
snakemake -j2 strand_check
```
Then check `strandedness.tsv` in the current working directory. For single-end, it looks something like:
```
sample      undetermined  ++,--       +-,-+
sample1     0.1099        0.4545      0.4356
sample2     0.2011        0.4090      0.3899
sample3     0.1909        0.4105      0.3985
sample4     0.1919        0.4142      0.3939
```
(see …
> Add strand check rule

- workflows/rnaseq/downstream/gene-patterns.Rmd
- workflows/rnaseq/downstream/rnaseq.Rmd
Attach the degPattern cluster IDs to the exported TSVs. This allows to automatically get the symbol then.
The added cluster column has the option of adding a label to have a unique column name, in case degPatterns is run multiple times -- in that case, it would add multiple columns to the output.
> Add cluster ids to exported results

- lib/lcdbwf/R/helpers.R
Fix issue with rownames in `counts.df` when technical replicates were collapsed.
Also includes a fix for keeping full name of _PAR_Y genes in `remove.version`.
> fix counts.df with collapsed technical replicates

- workflows/rnaseq/downstream/functional-enrichment.Rmd
`clusterProfiler::bitr` sometimes causes issues, ` AnnotationDbi::select` can be used instead in the functional-enrichment.Rmd.
> use AnnotationDbi::select rather than bitr

- workflows/rnaseq/Snakefile
This PR should hopefully free up a bit of disk space and clutter: it marks the "raw" bam files and rrna bams as temporary.
The featureCounts rule now uses the markdups bam as input, not the raw aligned bam.
**This change will give different results in cases where a user has run featureCounts with the `--ignoreDup` option.**
> featurecounts uses markdups bam; remove rrna and raw bam from multiqc

- .circleci/config.yml
Just found out over on https://github.com/lcdb/lcdb-wf/pull/347 that circleci tests are failing due to something going on with the container setup. This PR will be used to get that working again, and then squashed to target v1.9rc branch.
> fix circleci container setup

- docs/rnaseq-rmd.rst
- workflows/rnaseq/downstream/rnaseq.Rmd
Previously, v1.9rc required contrast names to follow the format `contr_[name]`, where [name] was used to alphabetically sort the output summary tables. To add flexibility, this branch requires the format `contr_NN_[name]`, where NN is a two-digit numeric index used to sort the contrasts. Users can modify NN to alter the order in which the contrast appears in output data tables. Documentation & example contrasts are update to reflect this change, as well. Addresses Issue #359
> require contrast names include sorting index

- lib/lcdbwf/R/annotations.R
- workflows/rnaseq/downstream/config.yaml
This addresses #357 by allowing permissions of AnnotationHub cache files, as discussed at https://github.com/Bioconductor/AnnotationHub/issues/31. It leaves the lockfile in place, but before returning the AnnotationHub object it modifies permissions to 660 (if specified in the config).
> support fixing group permissons on AnnotationHub cache

- workflows/rnaseq/Snakefile
```
-p                  If specified, fragments (or templates) will be counted
instead of reads. This option is only applicable for
paired-end reads; single-end reads are always counted as
reads.
-B                  Only count read pairs that have both ends aligned.
...
```
```
-p                  Specify that input data contain paired-end reads. To
perform fragment counting (ie. counting read pairs), the
'--countReadPairs' parameter should also be specified in
addition to this parameter.
--countReadPairs    Count read pairs (fragments) instead of reads. This option
is only applicable for paired-end reads.
-B                  Only count read pairs that have both ends aligned.
...
```
> Update Snakefile - add `--countReadPairs` for PE featureCounts

- workflows/chipseq/Snakefile
- workflows/rnaseq/Snakefile
- Removed the unused r1-only=False parameter in the render_r1_r2() function in both the rnaseq and chipseq Snakefiles
- Changed the name of 'r1_only' function to 'render_r1_only' in both Snakefiles to make the name more intuitive and updated function calls accordingly
> Fixed render_r1_r2 function(s) in Snakefiles

- workflows/rnaseq/Snakefile
Move `strand_arg` assignment from the `run` block to the `params` block so that `--rerun-trigger` will detect changes to strandedness configuration and re-run those rules
> Make strand_arg a param

- lib/helpers.py
- lib/patterns_targets.py
- workflows/rnaseq/Snakefile
- workflows/rnaseq/config/rnaseq_patterns.yaml
Change the directory where SRA fastq files are downloaded and add the 'orig_filename' column to the config object for each sample so that the rest of the workflow works correctly
> Change SRA fastq directory
